[node]
# the private spend key of the signer
signer-key = "56a7904a2dfd71c397bb48584033d8cb6ddcde9b46b7d91f07d2ede061723a0b"
# limit the peers that can establish a connection and exchange snapshots
consensus-only = false
# the period in seconds to check some mint and election kernel opportunities
kernel-operation-period = 700
# the maximum cache size in MB
memory-cache-size = 16384
# how many seconds to keep unconfirmed transactions in the cache storage
# this also limits the confirmed snapshots finalization cache to peer
cache-ttl = 7200

[storage]
# enable value log gc will reduce disk storage usage
value-log-gc = true

[network]
# the public endpoint to receive peer packets, may be a proxy or load balancer
# must be a public reachable domain or IP, and the port allowed by firewall
listener = "mixin-node.example.com:7239"
# whether to gossip known neighbors to neighbors, and to connect neighbors gossiped
# by neighbors
gossip-neighbors = true
# the nodes list
peers = [
  "mixin-node-01.b1.run:7239",
  "mixin-node-02.b1.run:7239",
  "mixin-node-03.b1.run:7239",
  "mixin-node-04.b1.run:7239",
  "mixin-node-05.b1.run:7239",
  "mixin-node-07.b1.run:7239",
  "34.67.143.156:7239",
  "34.82.0.191:7239",
  "mixin-node0.exinpool.com:7239",
  "mixin-node1.exinpool.com:7239",
  "mixin-node2.exinpool.com:7239",
  "35.188.242.130:7239",
  "35.245.207.174:7239",
  "35.185.16.229:7239",
  "35.247.51.107:7239",
  "35.227.72.6:7239",
  "mixin-node.poolin.com",
  "34.83.129.200:7239",
  "34.122.55.23:7239",
  "34.135.193.230:7239",
  "35.233.138.56:7239",
  "34.66.213.188:7239",
  "13.52.220.35:7239",
  "3.15.58.214:7239",
  "44.242.167.156:7239",
  "44.234.120.216:7239",
  "18.222.200.122:7239",
  "18.224.233.177:7239",
  "54.188.62.72:7239",
  "node-okashi.mixin.fan:7239",
  "node-42.f1ex.io:7239",
  "node-fes.f1ex.io:7239",
  "mixin-node-01.b.watch:7239",
  "mixin-node-02.b.watch:7239",
  "mixin-node-03.b.watch:7239",
  "lehigh.hotot.org:7239",
  "lehigh-2.hotot.org:7239",
]

[rpc]
# whether respond the runtime of each RPC call
runtime = false

[dev]
# whether to enable the pprof web server
profile = false
